import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity


EMBEDDING_MODEL_NAME = "BAAI/bge-m3"
FALLBACK_EMBEDDING_MODEL_NAME = "all-MiniLM-L6-v2"
model = None


def get_embedding_model():
    global model

    if model is not None:
        return model

    try:
        from sentence_transformers import SentenceTransformer
    except ImportError:
        model = False
        return None

    try:
        model = SentenceTransformer(EMBEDDING_MODEL_NAME)
    except Exception:
        model = SentenceTransformer(FALLBACK_EMBEDDING_MODEL_NAME)

    return model


def chunk_text(text, chunk_size=384, overlap=64):
    """
    Split text into overlapping chunks targeting the 256-512 token range.
    """
    words = text.split()

    if len(words) == 0:
        return []

    chunks = []
    start = 0

    while start < len(words):
        end = start + chunk_size
        chunk = " ".join(words[start:end])
        chunks.append(chunk)
        start += chunk_size - overlap

    return chunks


def build_vector_index(documents):
    """
    Build dense and sparse retrieval data from processed documents.
    """
    all_chunks = []

    for doc in documents:
        chunks = chunk_text(doc["text"])

        for chunk in chunks:
            all_chunks.append({
                "document_name": doc["document_name"],
                "text": chunk
            })

    if len(all_chunks) == 0:
        return None

    texts = [chunk["text"] for chunk in all_chunks]
    embedding_model = get_embedding_model()

    vectorizer = TfidfVectorizer(stop_words="english")
    sparse_matrix = vectorizer.fit_transform(texts)
    embeddings = None

    if embedding_model is not None:
        embeddings = embedding_model.encode(
            texts,
            convert_to_numpy=True,
            normalize_embeddings=True
        )

    index_data = {
        "chunks": all_chunks,
        "embeddings": embeddings,
        "vectorizer": vectorizer,
        "sparse_matrix": sparse_matrix,
    }

    return index_data


def answer_question(question, index_data, top_k=3):
    """
    Basic retrieval-based answer.
    For now, answer is generated by returning the most relevant chunks.
    Later, connect this to an LLM for generated answers.
    """
    if index_data is None:
        return "No indexed document content available.", []

    embedding_model = get_embedding_model()
    sparse_query = index_data["vectorizer"].transform([question])
    sparse_scores = cosine_similarity(sparse_query, index_data["sparse_matrix"]).flatten()

    if embedding_model is not None and index_data.get("embeddings") is not None:
        question_embedding = embedding_model.encode(
            [question],
            convert_to_numpy=True,
            normalize_embeddings=True
        )
        dense_scores = np.dot(index_data["embeddings"], question_embedding[0])
        combined_scores = (0.7 * dense_scores) + (0.3 * sparse_scores)
    else:
        combined_scores = sparse_scores

    indices = np.argsort(combined_scores)[::-1][:top_k]

    retrieved_sources = []

    for idx in indices:
        if idx != -1:
            source = dict(index_data["chunks"][idx])
            source["retrieval_score"] = round(float(combined_scores[idx]), 4)
            retrieved_sources.append(source)

    if len(retrieved_sources) == 0:
        return "I could not find relevant information from the processed documents.", []

    combined_context = "\n\n".join([source["text"] for source in retrieved_sources])

    answer = (
        "Based on the retrieved document content, the most relevant information is:\n\n"
        f"{combined_context[:1000]}"
    )

    return answer, retrieved_sources
